// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueueDeclare struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Exclusive            bool     `protobuf:"varint,2,opt,name=Exclusive,proto3" json:"Exclusive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueDeclare) Reset()         { *m = QueueDeclare{} }
func (m *QueueDeclare) String() string { return proto.CompactTextString(m) }
func (*QueueDeclare) ProtoMessage()    {}
func (*QueueDeclare) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *QueueDeclare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueDeclare.Unmarshal(m, b)
}
func (m *QueueDeclare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueDeclare.Marshal(b, m, deterministic)
}
func (m *QueueDeclare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueDeclare.Merge(m, src)
}
func (m *QueueDeclare) XXX_Size() int {
	return xxx_messageInfo_QueueDeclare.Size(m)
}
func (m *QueueDeclare) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueDeclare.DiscardUnknown(m)
}

var xxx_messageInfo_QueueDeclare proto.InternalMessageInfo

func (m *QueueDeclare) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueueDeclare) GetExclusive() bool {
	if m != nil {
		return m.Exclusive
	}
	return false
}

func init() {
	proto.RegisterType((*QueueDeclare)(nil), "main.QueueDeclare")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc,
	0x53, 0x72, 0xe0, 0xe2, 0x09, 0x2c, 0x4d, 0x2d, 0x4d, 0x75, 0x49, 0x4d, 0xce, 0x49, 0x2c, 0x4a,
	0x15, 0x12, 0xe2, 0x62, 0xf1, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02,
	0xb3, 0x85, 0x64, 0xb8, 0x38, 0x5d, 0x2b, 0x92, 0x73, 0x4a, 0x8b, 0x33, 0xcb, 0x52, 0x25, 0x98,
	0x14, 0x18, 0x35, 0x38, 0x82, 0x10, 0x02, 0x49, 0x6c, 0x60, 0xe3, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xe3, 0x9b, 0x3c, 0x99, 0x60, 0x00, 0x00, 0x00,
}
